name: Threat Composer App GitHub Actions CI/CD pipeline

on: 
  push:
    branches:
      - master     # plan prod
      - feat*      # plan only for non-prod
  workflow_dispatch:  # for manual runs
env:
    AWS_REGION: eu-west-2
    ECR_REPO_NAME: threat-composer-repo
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf_infra

    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-aws-connect
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Trivy IaC Scan (Terraform)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          scan-ref: tf_infra
          format: "table"
          exit-code: "0" 
          ignore-unfixed: true

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output
      
      - name: Terraform Show - Resource Summary
        run: terraform show -no-color | grep '^#'
  
  docker-build-deploy:
    runs-on: ubuntu-latest
    needs: terraform
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-aws-connect
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO_NAME: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG ./app
          docker push $ECR_REGISTRY/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG
          echo "image_url=$ECR_REGISTRY/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG" >> $GITHUB_ENV
